### ISSUE TITLE
Issue 6 User can delete character entries

### ISSUE THREAD

**Issue by KrisMackenroth** [KrisMackenroth/ajax-project#13]
## ⚙️ Feature
Users will be able to delete created characters from the entries list.

## 📐 Functionality
If the user clicks the delete anchor for an entry, a modal will be promoted asking to confirm the delete. If it is confirmed, the entry will be removed from the list and deleted from local storage.
## 🖼️ Wireframes
![Screenshot (562)](https://user-images.githubusercontent.com/103297457/174148618-f4d49845-128f-40f3-bfa6-4b0155484169.png)
![Screenshot (559)](https://user-images.githubusercontent.com/103297457/174148541-93e557dc-d28d-4cdd-83ca-5989bc45b485.png)
![Screenshot (561)](https://user-images.githubusercontent.com/103297457/174148556-f0c82c5b-f036-4f26-830a-4a512664eaa6.png)
## ✅ Task List

- [ ] Add a delete button to the character entries page for each character saved.
- [ ] Add an event listener to the delete button that listens for a click event.
- [ ] If a click event fires, a modal will pop up confirming if the user wants to delete that character, or if they want to cancel.
- [ ] If they confirm the delete, the character will be removed from local storage and deleted.
  - [ ] Remove all console logs.
  - [ ] Remove all commented-out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
