### ISSUE TITLE
Issue 8 User can input a chosen name

### ISSUE THREAD

**Issue by KrisMackenroth** [KrisMackenroth/ajax-project#17]
## ⚙️ Feature

Users will be able to input a specific name for a character.

## 📐 Functionality

Users will be presented with an input text for their character's name. The name input will have the default value of random. If the user begins typing a name, that name will be assigned to that character and will not be regenerated if the character's other features are regenerated. 

## 🖼️ Wireframes
![Screenshot (569)](https://user-images.githubusercontent.com/103297457/175454496-6c963a0a-0e25-42a2-b47c-ab5c4427d292.png)
![Screenshot (570)](https://user-images.githubusercontent.com/103297457/175454511-be50e9bb-8903-4ad1-8739-6076513680c2.png)
## ✅ Task List
- [ ] Create input for users to enter characters' names.
- [ ] If the input is left random, ensure that the character's name is populated from the name API.
  - [ ] Ensure the name is not randomized if the created character is regenerated.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
