### ISSUE TITLE
Issue 9 User can regenerate stats

### ISSUE THREAD

**Issue by KrisMackenroth** [KrisMackenroth/ajax-project#18]
## ⚙️ Feature

Users will be able to regenerate character stats if the random option is chosen for specific or all stats. 

## 📐 Functionality

Users will have the option to select a specific number ranging from 0 - 20 or random for all stats. If they choose a specific number, that stat will be locked in at that number. If they choose random, that stat will be randomized and can be regenerated each time the regenerated button is clicked on a character entry sheet. 

## 🖼️ Wireframes
![Screenshot (573)](https://user-images.githubusercontent.com/103297457/175456876-35642acf-bb13-496b-9945-7580f2c14412.png)
![Screenshot (574)](https://user-images.githubusercontent.com/103297457/175456887-a70f4fef-4409-4919-a093-d027ff7fb8a7.png)
## ✅ Task List

- [ ] Make sure that stat select options include random.
- [ ] If random is selected, make sure that a random number is generated from 0 to 20 and assigned to the specific stat. 
  - [ ] If a character is regenerated, make sure that stats that were generated with the random value selected, are regenerated every time the character is regenerated.
  - [ ] Remove all console logs.
  - [ ] Remove all commented-out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
